server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_PORT_5432_TCP_ADDR:localhost}:${POSTGRES_PORT_5432_TCP_PORT:5432}/warehouse
    username: postgres
    password: sprio
  jpa:
    hibernate:
      ddl-auto: validate
